import './assets/assets';
import { Inter } from 'next/font/google';
import Header from './components/header/header';
import Footer from './components/footer/footer';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Wandry Martinez | Portafolio',
    description: 'Generated by create next app',
    favicon: 'favicon.ico'
}

export default function RootLayout({ children }) {
    return (
        <html lang="en-EN">
            <body id={'body'} className={inter.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
