import { Inter } from 'next/font/google';
import { Metadata } from 'next';
import '@/app/assets/assets';
import SideNav from './components/common/sidenav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={false}>
      <body id={'body'} className={`${inter.className} antialiased`}>
        <div className="containers mx-auto px-4 lg:px-2">
          <article className="relative mt-0 flex h-screen w-full flex-col overflow-auto lg:mt-0 lg:flex-row lg:gap-5 lg:px-4">
            <header className="mb-20 max-h-[calc(100vh-6rem)] w-full pb-10 pt-5 sm:mb-0 lg:sticky lg:top-0 lg:max-w-[350px]">
              <SideNav />
            </header>
            <main className="w-7/10 overflow-auto">{children}</main>
          </article>
        </div>
      </body>
    </html>
  );
}
